version: '3.4'

services:
  serverDevagram:
    container_name: db-devagram
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'Leite.tjs@gmail.com'

  # api:
  #   container_name: apiDevagram
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - serverDevagram
